name: ZigbeeAttendo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  pie_chart: ^5.4.0
  http: ^1.2.2
  intl: ^0.20.1
  mysql1: ^0.20.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  mqtt_client: ^10.5.1
  mockito: ^5.4.5
  build_runner: ^2.4.14
  dio: ^5.8.0+1
  file_picker: ^9.0.0
  excel: ^4.0.6
  shared_preferences: ^2.5.2
  web_socket_channel: ^3.0.2
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  flutter_background: ^1.3.0+1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  permission_handler: ^11.4.0
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.0
  flutter_animated_button: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.8
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/who.jpg
    - assets/images/base.jpg
    - assets/images/logo.png
    - assets/loading.json
    - assets/login_successful.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # Path to your app icon

flutter_native_splash:
  color: "#ffffff"  # Change this to match your app's background color
  image: assets/images/logo.png  # Make sure you have this image
  android: true
  ios: true
